### ISSUE TITLE
请问百鸽API有数据版本的接口吗?

### ISSUE THREAD

**Issue by RyoLee** [mercury233/mercury233.github.io#60]
这个项目[Gevjon](https://github.com/RyoLee/Gevjon/)在使用百鸽的[数据](https://ygocdb.com/api/v0/cards.zip),请问数据版本有对应的api获取吗?本来是想用HEAD取头部用size检查版本,但是看了下网站有cloudflare的HTTP/2配置,在HTTP/2中Content-Length已经弃用导致此路不通,请问能否添加一个类似cards.zip.md5的文件用于存储cards.zip的hash值用于判断?

**Comment by mercury233** [comment]
没做，我研究一下怎么提供一个接口吧

**Comment by mercury233** [comment]
https://ygocdb.com/api/v0/cards.zip.md5?callback=gu
加上了，也可以不用callback

**Comment by RyoLee** [comment]
多谢!
